apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
          - name: zad2gitops
            image: redek/zad2gitops:latest
            command: [sh, -e, -c]
            args:
              - git clone https://github.com/Redeek/Zad10-Config.git /tmp/Zad10-Config &&
                find /tmp/Zad10-config -name '*.yaml' -exec kubectl apply -f {} \
                
                
                
                
                
                
                